Update open-ai-app.yml

diff --git a/.github/workflows/open-ai-app.yml b/.github/workflows/open-ai-app.yml
--- a/.github/workflows/open-ai-app.yml
+++ b/.github/workflows/open-ai-app.yml
@@ -82,12 +82,18 @@ jobs:
         uses: azure/CLI@v1
         with:
           inlineScript: |
-            rg=$(az webapp list --query "[?name=='${{ secrets.AZURE_APP_SERVICE_NAME }}'].resourceGroup" --output tsv)
-            echo Setting SCM_DO_BUILD_DURING_DEPLOYMENT=false on app service ${{ secrets.AZURE_APP_SERVICE_NAME }}
-            az webapp config appsettings set -n ${{ secrets.AZURE_APP_SERVICE_NAME }} -g $rg --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false -o none
-            echo Setting --startup-file=\"node server.js\" on app service ${{ secrets.AZURE_APP_SERVICE_NAME }}
-            az webapp config set --startup-file="node server.js" -n ${{ secrets.AZURE_APP_SERVICE_NAME }} -g $rg -o none
-            sleep 10
+            rg=$(az webapp list --query "[?name=='${AZURE_APP_SERVICE_NAME}'].resourceGroup" --output tsv)
+            if [ -z "$rg" ]
+            then
+              echo "Resource group could not be found for the given web app name. Please check the web app name."
+              exit 1
+            fi
+            echo Setting SCM_DO_BUILD_DURING_DEPLOYMENT=false on app service ${AZURE_APP_SERVICE_NAME} in slot ${AZURE_SLOT}
+            az webapp config appsettings set -n ${AZURE_APP_SERVICE_NAME} -g $rg --slot ${AZURE_SLOT} --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false -o none
+            echo Setting --startup-file=\"node server.js\" on app service ${AZURE_APP_SERVICE_NAME} in slot ${AZURE_SLOT}
+            az webapp config set --startup-file="node server.js" -n ${AZURE_APP_SERVICE_NAME} -g $rg --slot ${AZURE_SLOT} -o none
+
+sleep 10
 
       - name: 🚀 Deploy to Azure Web App
         id: deploy-to-webapp
